env:
 - CHRONOSVERSION: 3.0.2

language: python
python:
  - 2.7
  - 3.5
sudo: required
services:
  - docker
before_install:
  - docker-compose -f itests/docker-compose.yml pull
install:
  - pip install tox
script:
  - make test && make itests
