env:
 - CHRONOSVERSION: 2.3.4
 - CHRONOSVERSION: 2.4.0

language: python
python:
  - 2.7
  - 3.5
sudo: true
dist: trusty
install:
  - pip install tox
script:
  - ./itests/install-chronos.sh
  - ./itests/start-chronos.sh
  - make test && make itests
