version: "2"

services:
  zookeeper:
    image: zookeeper:3.4.9
    container_name: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZK_INIT_LIMIT: 10
      ZK_SYNC_LIMIT: 5

  master:
    image: mesosphere/mesos-master:1.0.3
    container_name: mesos-master
    environment:
      MESOS_ZK: zk://zookeeper:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: chronos-python
      MESOS_REGISTRY: in_memory
      MESOS_HOSTNAME: localhost
    ports:
      - 5050:5050
    depends_on:
      - zookeeper
    links:
      - zookeeper

  agent:
    image: mesosphere/mesos-slave:1.0.3
    container_name: mesos-agent
    pid: host
    environment:
      MESOS_MASTER: zk://zookeeper:2181/mesos
      MESOS_WORK_DIR: /tmp/mesos
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_CONTAINERIZERS: mesos
      MESOS_HOSTNAME: localhost
    ports:
      - 5051:5051
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    depends_on:
      - zookeeper
    links:
      - zookeeper
      - master

  chronos-2.4.0:
    image: mesosphere/chronos:chronos-2.4.0-0.1.20150828104228.ubuntu1404-mesos-0.27.0-0.2.190.ubuntu1404
    container_name: chronos-2.4.0
    command: '/usr/bin/chronos run_jar --http_port 4400 --zk_hosts zookeeper:2181 --master zk://zookeeper:2181/mesos'
    ports:
      - 4400:4400
    depends_on:
      - zookeeper
      - master
    links:
      - zookeeper
      - master

  chronos-3.0.2:
    image: mesosphere/chronos:v3.0.2
    container_name: chronos-3.0.2
    command: '--zk_hosts zookeeper:2181 --master zk://zookeeper:2181/mesos'
    environment:
      PORT0: 4400
      PORT1: 8080
    ports:
      - 4400:4400
    depends_on:
      - zookeeper
      - master
    links:
      - zookeeper
      - master

